#include<bits/stdc++.h>
using namespace std;

/*  Problem - Subsequences of String
    Problem Statement
    You are given a string 'STR' containing lowercase English letters from a to z inclusive. 
    Your task is to find all non-empty possible subsequences of 'STR'.
    A Subsequence of a string is the one which is generated by deleting 0 or more letters 
    from the string and keeping the rest of the letters in the same order.

    Sample Input 1:
    abc

    Sample Output 1:
    a ab abc ac b bc c
*/

// CodingNinjas link [https://www.codingninjas.com/studio/problems/subsequences-of-string_985087?leftPanelTab=0&utm_source=youtube&utm_medium=affiliate&utm_campaign=love_babbar_16]

void solve(string str, string inner, vector<string> &outer, int index){
	// creating base case
	if(index >= str.length()){
		if(inner.length()>0)
		outer.push_back(inner);
		return;
	}

	// exlude code
	solve(str, inner, outer, index+1);

	// include code
	inner.push_back(str[index]);
	solve(str, inner, outer, index+1);
}

vector<string> subsequences(string str){
	vector<string> outer;
	string inner = "";
	int index=0;
	solve(str, inner, outer, index);
	return outer;
}